- src/DotNetCore.CAP.SqlServer/CAP.EFOptions.cs
- src/DotNetCore.CAP.SqlServer/CAP.SqlServerOptions.cs
- src/DotNetCore.CAP.SqlServer/SqlServerMonitoringApi.cs
Our SqlServer is still 2008 but wasn't supported by CAP. I do see that SqlServer2008 is too old, but upgrading db is too hard to complete. However, it's easy to be compatible with SqlServer2008.
Usage:
`options.UseEntityFramework<MessageContext>(x =>
{
x.UseSqlServer2008();
});`
or `options.UseSqlServer(x =>
{
x.UseSqlServer2008();
});`
And will not affect others who uses SqlServer2012.
> Compatible sqlserver2008

- samples/Sample.RabbitMQ.MongoDB/Controllers/ValuesController.cs
- src/DotNetCore.CAP.MongoDB/CAP.MongoDBCapOptionsExtension.cs
- src/DotNetCore.CAP.MongoDB/CapPublisher.cs
- src/DotNetCore.CAP.MongoDB/MongoTransaction.cs
- src/DotNetCore.CAP/Abstractions/CapPublisherBase.cs
- src/DotNetCore.CAP/Abstractions/IMongoTransaction.cs
- src/DotNetCore.CAP/ICapPublisher.cs
- test/DotNetCore.CAP.Test/CAP.BuilderTest.cs
Improve the usage like this:
```c#
using (var trans = await _mongoTransaction.BegeinAsync())
{
repository.InsertOne(trans.GetSession(), someValue);
await _capPublisher.PublishWithMongoAsync("sample.rabbitmq.mongodb", DateTime.Now, trans);
}
```
> Abstract MongoTransaction to make the usage more comfortable

- src/DotNetCore.CAP.MongoDB/ICollectProcessor.MongoDB.cs
- src/DotNetCore.CAP.MongoDB/IStorageTransaction.MongoDB.cs
After `DotNetCore.CAP.MongoDB` updated to 2.4, there was a bug. This PR fixed that.
```
[Error] An exception occurred while executing the subscription method. Topic:Feed.Created, Id:1075252961419243520
System.FormatException: Element 'Version' does not match any field or property of class DotNetCore.CAP.Models.CapReceivedMessage.
at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeClass(BsonDeserializationContext context)
at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
at MongoDB.Driver.Core.Operations.ElementDeserializer`1.Deserialize(BsonDeserializati …
```
> Fix that Version doesn't match

- src/DotNetCore.CAP/Processor/IProcessor.NeedRetry.cs
When the `IStorageConnection` service is down, `connection.GetPublishedMessagesOfNeedRetry()` and `connection.GetReceivedMessagesOfNeedRetry()` both throw an exception.
The wait operation in `ProcessAsync` is therefore never executed.
We therefore end up in an infinite loop of immediate retries until the `IStorageConnection` service is back up. This can be seen in the logs where we have hundreds of "Processor 'DotNetCore.CAP.Processor.NeedRetryMessageProcessor' failed. Retrying..." entries per second.
We add a try/catch around the message retrieval operation and log the error. The next messages retrieval will therefore be executed `options.FailedRetryInterval` seconds later.
> Handle messages retrieval failure

- src/DotNetCore.CAP/Diagnostics/TracingHeaders.cs
在启用 CapBeforePublish 后 发送消息时会导致空引用异常
when DiagnosticListener enabled, publish message will cause null reference exception
Call Stack:
TracingHeaders.GetEnumerator
TracingHeaders.IEnumerable.GetEnumerator
ToJObject
Helper.AddTracingHeaderProperty
BasePublishMessageSender.SendWithoutRetryAsync
BasePublishMessageSender.SendAsync
NeedRetryMessageProcessor.ProcessPublishedAsync
NeedRetryMessageProcessor.ProcessAsync
BasePublishMessageSender.SendWithoutRetryAsync
BasePublishMessageSender.SendAsync
> fix NullReferenceException

- src/DotNetCore.CAP/CAP.ServiceCollectionExtensions.cs
- src/DotNetCore.CAP/ConsumerExecutorDescriptor.cs
- src/DotNetCore.CAP/IConsumerServiceSelector.Default.cs
- src/DotNetCore.CAP/Internal/IConsumerInvoker.Default.cs
**目前的方式是：**
1. 通过查找 IServiceCollection 中包含 ICapSubscribe 接口的服务实现类型，并重新注册到 ICapSubscribe 下。
2. 通过获取 ICapSubscribe 的全部服务来找到之前的服务实现类型，再找出其中的订阅方法。
3. 消息在执行的时候，尝试获取或创建该服务实现类型的服务。
**目前方法存在以下问题：**
1. 在第2步时，会实例化一次服务。
2. 在第3步，如果 ServiceType 和 ImplementationType 为不同类型时，此时又会实例化一次服务。
3. 对于注册为**Singleton**类型服务，会被非预期的实例化了多次。某些服务可能会在构造方法中执行其他操作，及执行的实例不一致，可能会导致一些非预期的结果。
**问题示例**
注册为**Singleton**类型服务，且 ServiceType 和 ImplementationType 为不同类型。服务内有个私有的缓存，在收到某个订阅消息后，清理部分缓存。
目前的方式，该服务类型实际上会被实例化了3个：注册为 ServiceType 的、注册为 ICapSubscribe 的，以及注册为 ImplementationType 的。
此时，在 Controller 或者其他服务中，通过 serviceProvider.GetService<ServiceType>() 获取到的实例，与 执行订阅消息的实例并不是同一个。导致该订阅消息没有在正确的实例上执行。
---------------------------
**本次提交的 patch 可解决以上问题：**
1. 直接从保存的 IServiceCollection 中查找包含 ICapSubscribe 接口的 ImplementationType，再找出其中的订阅方法并记录 …
> Try to get the service instance using the serviceProvider.GetServices method.

- src/DotNetCore.CAP/Abstractions/CapPublisherBase.cs
- src/DotNetCore.CAP/Diagnostics/DiagnosticListenerExtensions.cs
- src/DotNetCore.CAP/Diagnostics/EventData.Broker.Store.cs
With these changes, it will be possible to add TracingHeaders to message on `CapBeforePublishMessageStore` event just like before `WritePublishBefore` and `WriteConsumeBefore` (although Headers property doesn't work for `WriteConsumeBefore`, at least I can change message Content directly)
> Write publish message store

- src/DotNetCore.CAP/Dashboard/CAP.DashboardMiddleware.cs
- src/DotNetCore.CAP/Dashboard/IDashboardAuthorizationFilter.cs
- src/DotNetCore.CAP/Dashboard/LocalRequestsOnlyAuthorizationFilter.cs
在自定义IDashboardAuthorizationFilter 的过程中,我发现在Authorize里无法使用异步方法,而观察asp.net core原生代码,这类方法多是支持异步的.
https://github.com/aspnet/Security/blob/26d27d871b7992022c082dc207e3d126e1d9d278/src/Microsoft.AspNetCore.Authentication/AuthenticationMiddleware.cs#L54
期待改进
> change DashboardMiddleware to async

- src/DotNetCore.CAP.SqlServer/IMonitoringApi.SqlServer.cs
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'id'.
> Dashboard - Invalid column name 'id'.

- src/DotNetCore.CAP.Kafka/ITransport.Kafka.cs
- src/DotNetCore.CAP.Kafka/KafkaConsumerClient.cs
- src/DotNetCore.CAP.Kafka/KafkaHeaders.cs
We need the ability to set the message key of Kafka messages sent via CAP. I've implemented this as an option here in a _far_ less invasive way than in #397.
If you add the `KafkaHeaders.KafkaKey` header, it will use the value as the Kafka message key. Otherwise the behavior will be as before.
> Add capability to optionally set kafka message key via new header

- src/DotNetCore.CAP.Kafka/KafkaConsumerClient.cs
This caused any messages published by CAP with a kafka key set to not be consumable by CAP.
> Removes line that added the kafka key to headers an extra time.

- samples/Sample.RabbitMQ.MySql/Controllers/ValuesController.cs
- src/DotNetCore.CAP.MySql/DotNetCore.CAP.MySql.csproj
- src/DotNetCore.CAP.MySql/IDataStorage.MySql.cs
- src/DotNetCore.CAP.MySql/IMonitoringApi.MySql.cs
- src/DotNetCore.CAP.MySql/IStorageInitializer.MySql.cs
- test/DotNetCore.CAP.MySql.Test/ConnectionUtil.cs
MySqlConnector 1.0 changes the primary namespace to `MySqlConnector`: mysql-net/MySqlConnector#824; this updates all relevant code.
This starts the discussion around updating MySqlConnector to 1.0, but doesn't need to be merged until it's out of beta.
> Update MySqlConnector to 1.0

- src/DotNetCore.CAP.MongoDB/IDataStorage.MongoDB.cs
Updated query as it referenced the wrong collection as a result after 3 retries the old messages are never processed (<4min)
> Updated mongo db query.

- README.md
- src/DotNetCore.CAP.Dashboard/Pages/SubscriberPage.cshtml
- src/DotNetCore.CAP.Dashboard/Pages/SubscriberPage.generated.cs
- src/DotNetCore.CAP/CAP.Attribute.cs
- src/DotNetCore.CAP/Internal/ConsumerExecutorDescriptor.cs
- src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs
- src/DotNetCore.CAP/Internal/IConsumerServiceSelector.Default.cs
- src/DotNetCore.CAP/Internal/TopicAttribute.cs
- test/DotNetCore.CAP.Test/ConsumerServiceSelectorTest.cs
Adds the functionality described in issue [#613](https://github.com/dotnetcore/CAP/issues/613)
Quoted from the updated `README.md`:
To group topic subscriptions on class level you're able to define a subscription on a method as a partial. Subscriptions on the message queue will then be a combination of the topic defined on the class and the topic defined on the method. In the following example the `Create(..)` function will be invoked when receiving a message on `customers.create`
```c#
[CapSubscribe("customers")]
public class CustomersSubscriberService : ICapSubscribe
{
[CapSubscribe("create", isPartial: true)]
public void Create(Customer customer)
{
}
}
```
> partial topic attributes

- src/DotNetCore.CAP.PostgreSql/IMonitoringApi.PostgreSql.cs
- src/DotNetCore.CAP/Internal/IConsumerServiceSelector.Default.cs
fixed@When class is not marked CapSubscribe, the method not marked isPartial cannot be found #622 
fixed@CAP dashborad received list display wrong cloumn when I use PostgreSql #624
> fixed #622 #624

- src/DotNetCore.CAP/Internal/IConsumerServiceSelector.Default.cs
- test/DotNetCore.CAP.Test/ConsumerServiceSelectorTest.cs
> GetRuntimeMethods instead of DeclaredMethods to get inherited members.

- src/DotNetCore.CAP/CAP.Options.cs
- src/DotNetCore.CAP/Internal/ConsumerExecutorDescriptor.cs
- src/DotNetCore.CAP/Internal/ICapPublisher.Default.cs
- src/DotNetCore.CAP/Internal/IConsumerServiceSelector.Default.cs
- test/DotNetCore.CAP.Test/CustomConsumerSubscribeTest.cs
**Problem**
We have multiple instances of the app, which deployed to AWS in different VPCs but in the same region. In this scenario, isolation works perfectly except for SNS and SQS, which are shared within the region.
**Proposed solution**
Add to `CapOptions` prefixes for topic (`TopicNamePrefix `) and group (`GroupNamePrefix `) names to make these parameters unique for each application instance. These parameters are optional, and if not defined the behavior will remain unchanged.
> Add support for group and topic prefixes

- src/DotNetCore.CAP/Internal/IConsumerServiceSelector.Default.cs
- test/DotNetCore.CAP.Test/CustomConsumerSubscribeTest.cs
This is a fix to PR https://github.com/dotnetcore/CAP/pull/780
After additional verification, I have reverted my changes for assigning `TopicNamePrefix` to `key` in `ConsumerServiceSelector.SelectBestCandidate` because it is already contained in the key if the topic prefix was defined.
This bug affects only the case when `TopicNamePrefix` was defined in CAP options
> Fix topic selector in IConsumerServiceSelector

- src/DotNetCore.CAP.AmazonSQS/AmazonPolicyExtensions.cs
- src/DotNetCore.CAP.AmazonSQS/AmazonSQSConsumerClient.cs
- src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs
- src/DotNetCore.CAP/Transport/IConsumerClient.cs
There are few problems with `DotNetCore.CAP.AmazonSQS` provider. Our setup includes about 150 topics and about 15 queues. CAP is configured with `ConsumerThreadCount = 4`. This results in about 700 subscriptions.
**Problem 1**
When executing CAP with this configuration the subscription to SNS fails with the error `AmazonSimpleNotificationServiceException: Rate exceeded` and then required queues not created. This relates to the 
`snsClient.CreateTopicAsync` call and occurs because AWS cannot process so many concurrent requests of SNS topic creation at a time.
**Proposed solution to Problem 1**
Separate topic creation and subscription process (i.e. extract topic creation out of the consumer threads). I have added `FetchTopics` method to `IConsumerClient` which returns a list of topics by …
> Improvements to AWS topic subscription and SQS access policy generation

- src/DotNetCore.CAP.PostgreSql/IMonitoringApi.PostgreSql.cs
Was trying to filter the Dashboard by some of the message properties (content) and it was not working. After investigating, found out that the generated SQL as wrong. Since the % is already placed within the NpgsqlParameter on the line 94, the filter on the line 84 was wrongly placed and can be simplified.
This fixes this issue and the content filter now behaves properly.
> Fixed SQL content filter on IMonitoringApi.PostgreSql.cs

- samples/Sample.RabbitMQ.Postgres.DashboardAuth/Startup.cs
- src/DotNetCore.CAP.Dashboard/CAP.DashboardMiddleware.cs
- src/DotNetCore.CAP.Dashboard/CAP.DashboardOptions.cs
This PR adds a DefaultChallengeScheme property to CAP.DashboardOptions.cs that sets up the scheme to be used when the Dashboard uses authentication via Challenge using the ASP.NET middlewares. If none is setup, the default of the application will be used.
It is useful for application with multiple authentication schemes.
Updated the sample as well.
> Added DefaultChallengeScheme to Dashboard authentication middleware

- docs/content/user-guide/en/transport/azure-service-bus.md
- src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerClient.cs
- src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerCommitInput.cs
- src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusHeaders.cs
- src/DotNetCore.CAP.AzureServiceBus/CAP.AzureServiceBusOptions.cs
- src/DotNetCore.CAP.AzureServiceBus/ITransport.AzureServiceBus.cs
As discussed in #828, this is a PR to add session support for Azure Service Bus.
Adds a new config option `EnableSessions` for Azure Service Bus. Session support must be explicitly enabled. When disabled, CAP works like before.
When sessions are enabled:
* `RequiresSession` is set on auto-created subscriptions
* The `SessionId` property is set on the Service Bus Message
* uses the value of the `cap-session-id` header, when present
* otherwise falls back to using the message id (similar to the handling of `cap-kafka-key`)
* RegisterSessionHandler is used instead of RegisterMessageHandler when consuming events
There is also some brief documentation on the feature, how to enable and use it (in English, possibly needs translation?).
As we don't use CAP on the consumer side ourselves, this …
> Add support for Azure Service Bus sessions

- src/DotNetCore.CAP.AmazonSQS/ITransport.AmazonSQS.cs
- src/DotNetCore.CAP/OperateResult.cs
**Problem**
The `NullReferenceException` by `DotNetCore.CAP.Messages.MessageExtensions.AddOrUpdateException` when no SNS topics found in `AmazonSQSTransport`.
**Proposed solution**
This is related to the usage old overload of `OperateResult` in `AmazonSQSTransport`, which does not accept an exception. It is not valid anymore, since `MessageSender` expecting that exception is not null when message failed.
Removed obsolete overload `OperateResult Failed(params OperateError[] errors)` and used a recent one in `AmazonSQSTransport`
> Fix null reference in AmazonSQSTransport

- src/DotNetCore.CAP.SqlServer/Diagnostics/DiagnosticObserver.cs
DiagnosticObserver returns rather than using a possible null SqlConnection that may come from another component.
> DiagnosticObserver does not use null connection

- src/DotNetCore.CAP.RabbitMQ/IConnectionChannelPool.Default.cs
- src/DotNetCore.CAP.RabbitMQ/RabbitMQConsumerClient.cs
In the `Dispose` method of `RabbitMQConsumerClient`, the connection should not be closed because the connection is reused.  
#861
> Fix RabbitMQ connection was closed unexpectedly.

- src/DotNetCore.CAP/OperateResult.cs
Since there's no set opertions on `_errors`, we could make it `readonly`
> make OperateResult._errors readonly

- src/DotNetCore.CAP.PostgreSql/IDbContextTransaction.CAP.cs
Applying the same fix realized for sql server transaction interface ([issue explained here](https://github.com/dotnetcore/CAP/issues/867))  to the postgresql transaction interface.
Brief overview: the problem is that the EF Core GetDbTransaction method ([extension method reference](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Storage/DbContextTransactionExtensions.cs)) is throwing InvalidOperationException because the CAP PostgreSQL transaction class is not implementing the required interface so the extension method can be executed.
> Implementing IInfrastructure interface in order to the GetDbTransaction extension method of EF core work

- src/DotNetCore.CAP/CAP.Builder.cs
- src/DotNetCore.CAP/Internal/ConsumerContext.cs
- src/DotNetCore.CAP/Internal/Filter/ExceptionContext.cs
- src/DotNetCore.CAP/Internal/Filter/ExecutedContext.cs
- src/DotNetCore.CAP/Internal/Filter/ExecutingContext.cs
- src/DotNetCore.CAP/Internal/Filter/FilterContext.cs
- src/DotNetCore.CAP/Internal/Filter/ISubscribeFilter.cs
- src/DotNetCore.CAP/Internal/ISubscribeInvoker.Default.cs
- test/DotNetCore.CAP.Test/CAP.BuilderTest.cs
Since CAP does not have filters or interceptors, in some scenarios additional operations, such as logging or enabling transaction management, need to be performed before and after the subscriber's execution.
Prior to this, this can be achieved with the help of third-party AOP components, such as the behavior described in the [article](https://cap.dotnetcore.xyz/user-guide/zh/samples/castle.dynamicproxy/) . But there are some limitations and precautions, such as the need to mark the method as viusal or the constructor injection behavior of the proxy class becomes complicated. 
Based on the above reasons, it is necessary to provide support for Filter.
Provides support for custom filters through the `ISubscribeFilter` interface. Considering the complexity, currently does not provide support …
> Add subscribe filter support

- src/DotNetCore.CAP.Dashboard/CapCache.cs
- src/DotNetCore.CAP.Dashboard/NodeDiscovery/INodeDiscoveryProvider.Consul.cs
1，修正health check 路径为 'cap/api/health'
2，开放CapCache，可自实现INodeDiscoveryProvider
> fix:  health check path is changed to 'cap/api/health'

- src/DotNetCore.CAP.AmazonSQS/AmazonPolicyExtensions.cs
- src/DotNetCore.CAP.AmazonSQS/AmazonSQSConsumerClient.cs
- src/DotNetCore.CAP.AmazonSQS/ITransport.AmazonSQS.cs
- Added ability to create topic if it is not found in the topics cache
- Improved functions naming
**Problem 1**
In the production, we have faced [limitation of SQS policy](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/quotas-policies.html) - size 8192 b
**Proposed solution**
In previous PR https://github.com/dotnetcore/CAP/pull/808 I reduced policy size by combining statements for SNS access into one. Here I propose to replace all ARNs with wildcard if the prefixes for SNS and SQS name matches.
For example, there is SQS name `MyQueue` and three related topics:
```JSON
"Resource": "arn:aws:sqs:us-east-1:MyQueue-v1",
"Condition": {
"ArnLike": {
"aws:SourceArn": "arn:aws:sns:us-east-1:MyQueue-FirstTopic",
"aws:SourceArn": …
```
> Improvements to AWS provider

- src/DotNetCore.CAP.Kafka/IConnectionPool.Default.cs
- src/DotNetCore.CAP.Kafka/KafkaConsumerClient.cs
- src/DotNetCore.CAP.Kafka/KafkaConsumerClientFactory.cs
I would like control of the Kafka ProviderBuilder and ConsumerBuilder to allow decorators. 
No breaking changes. 
Opening up of visibility shouldn't affect performance as these classes are usually singletons and the methods are rarely called.
> Allows the overriding of the Kafka  ProviderBuilder and ConsumerBuilder 

- src/DotNetCore.CAP.AmazonSQS/AmazonSQSConsumerClient.cs
- src/DotNetCore.CAP.AmazonSQS/CAP.AmazonSQSOptions.cs
- src/DotNetCore.CAP.AmazonSQS/ITransport.AmazonSQS.cs
I had to work on local development environment, didn't test on AWS.
This PR is about #1029 
Also added serviceUrl parameters to Amazon SQS module configuration to support local development environments. If provided, these service url parameters override AWS region settings.
Example usage for localstack:
```
opts.UseAmazonSQS(conf =>
{
conf.SNSServiceUrl = "http://localhost:4566";
conf.SQSServiceUrl = "http://localhost:4566";
conf.Credentials = new Amazon.Runtime.BasicAWSCredentials("test", "test");
});
```
> Handling unobserved tasks of async method calls in Amazon SQS module and local development environment support

- CAP.sln
- README.md
- docs/content/user-guide/en/cap/configuration.md
- samples/Sample.RabbitMQ.SqlServer.DispatcherPerGroup/Controllers/HomeController.cs
- samples/Sample.RabbitMQ.SqlServer.DispatcherPerGroup/Messages/FastProcessingReceiver.cs
- samples/Sample.RabbitMQ.SqlServer.DispatcherPerGroup/Messages/SlowProcessingReceiver.cs
- samples/Sample.RabbitMQ.SqlServer.DispatcherPerGroup/Messages/TestMessage.cs
- samples/Sample.RabbitMQ.SqlServer.DispatcherPerGroup/Messages/VeryFastProcessingReceiver.cs
- samples/Sample.RabbitMQ.SqlServer.DispatcherPerGroup/Messages/XSlowProcessingReceiver.cs
- samples/Sample.RabbitMQ.SqlServer.DispatcherPerGroup/Program.cs
- samples/Sample.RabbitMQ.SqlServer.DispatcherPerGroup/Sample.RabbitMQ.SqlServer.DispatcherPerGroup.csproj
- samples/Sample.RabbitMQ.SqlServer.DispatcherPerGroup/Startup.cs
- samples/Sample.RabbitMQ.SqlServer.DispatcherPerGroup/TypedConsumers/QueueHandler.cs
- samples/Sample.RabbitMQ.SqlServer.DispatcherPerGroup/TypedConsumers/QueueHandlerTopicAttribute.cs
- samples/Sample.RabbitMQ.SqlServer.DispatcherPerGroup/TypedConsumers/QueueHandlersExtensions.cs
- samples/Sample.RabbitMQ.SqlServer.DispatcherPerGroup/TypedConsumers/TypedConsumerServiceSelector.cs
- samples/Sample.RabbitMQ.SqlServer.DispatcherPerGroup/appsettings.json
- src/DotNetCore.CAP/CAP.Builder.cs
- src/DotNetCore.CAP/CAP.Options.cs
- src/DotNetCore.CAP/CAP.ServiceCollectionExtensions.cs
- src/DotNetCore.CAP/Internal/ISubscribeDispatcher.Default.cs
- src/DotNetCore.CAP/Internal/LoggerExtensions.cs
- src/DotNetCore.CAP/Processor/IDispatcher.PerGroup.cs
This addition do not change anything to default behavior of CAP.
To run processing messages for each consumer group independently must set option `UseDispatchingPerGroup` to `true`. This will add to DI container `DispatcherPerGroup` instead of default `Dispatcher`.
With default `Dispatcher` behavior of CAP is:
As you can see `VeryFastProcessingReceiver` waits until `XSlowProcessingReceiver` finishes.
With `DispatcherPerGroup` behavior of CAP is:
Here we have situation where all subscribers pushes received messages to own dispatching channel. Each channel has set thread count to `ConsumerThreadCount` value.
New feature is used in new sample application `Sample.RabbitMQ.SqlServer.DispatcherPerGroup`.
> Added possibility to process messages for each consumer group independently

- CAP.sln
- docs/content/user-guide/en/cap/messaging.md
- docs/content/user-guide/en/transport/azure-service-bus.md
- samples/Sample.AzureServiceBus.InMemory/Program.cs
- samples/Sample.AzureServiceBus.InMemory/Sample.AzureServiceBus.InMemory.csproj
- samples/Sample.AzureServiceBus.InMemory/SampleSubscriber.cs
- samples/Sample.AzureServiceBus.InMemory/appsettings.Development.json
- samples/Sample.AzureServiceBus.InMemory/appsettings.json
- src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerClient.cs
- src/DotNetCore.CAP.AzureServiceBus/CAP.AzureServiceBusOptions.cs
This PR adds CustomHeaders support to the Azure Service Bus CAP transport.
Main changes:
- CustomHeaders property to src/DotNetCore.CAP.AzureServiceBus/CAP.AzureServiceBusOptions.cs
- CustomHeaders support in src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerClient.cs
- A sample with ASB transport and InMem storage
- Updated docs
> Added CustomHeaders support to Azure Service Bus transport

- src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusHeaders.cs
- src/DotNetCore.CAP.AzureServiceBus/ITransport.AzureServiceBus.cs
* Added support of ScheduledEnqueueTimeUtc  for AzureServiceBus transport
```cs
public class DemoController : ControllerBase
{
private readonly ICapPublisher _publisher;
private readonly ILogger<DemoController> _logger;
public DemoController(ICapPublisher publisher, ILogger<DemoController> logger)
{
_publisher = publisher;
_logger = logger;
}
[HttpPost("publish")]
public async Task Publish()
{
await _publisher.PublishAsync("demo-publish", string.Empty, new Dictionary<string, string?>
{
[AzureServiceBusHeaders.ScheduledEnqueueTimeUtc] = DateTimeOffset.UtcNow.AddSeconds(60).ToString(),
});
}
[CapSubscribe("demo-publish")]
public Task Subscribe()
{
_logger.LogInformation("RECEIVED!!");
return Task.CompletedTask;
}
}
```
> AzureServiceBus: add ScheduledEnqueueTimeUtc support

- samples/Sample.RabbitMQ.MongoDB/docker-compose.yml
- src/DotNetCore.CAP.MongoDB/IMonitoringApi.MongoDB.cs
When CAP is using MongoDB with a different element name convention registered in the convention registry, the queries does not work as expected.
This occurs because some queries are mapping properties as strings, and once a different case convention is registered (CamelCaseElementNameConvention, as example), they don't behave as expected.
In order to resolve this issue, I changed the queries to use LINQ instead of Bson Documents. I didn't try to abstract PublishedMessage and ReceivedMessage and simply encapsulate the necessary logic to behave accordingly in each case based on the message type.
> Fixes MongoDB queries not returning results when a element convention name is registered

- src/DotNetCore.CAP/Internal/IConsumerServiceSelector.Default.cs
if service or it's dependent services register with scop ， it can not resolve from root ServiceProvider
> fix Consumer Service register error when with scope lifetime

- build/version.props
- src/DotNetCore.CAP.RedisStreams/IRedisStream.Manager.Extensions.cs
Fixed RedisStream.Manager.Extensions.TryGetOrCreateStreamGroupAsync to create ConsumerGroup when not found.
> When using RedisStreams only one ConsumerGroup is created 

- src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs
这里原本应该是没有问题的，可能哪个版本不小心加了个日志进来，后果就非常可怕了。。
当mq里存在一个非标准的message，典型的是header里不存在`cap-msg-name`，由于在try外面使用了获取 `cap-msg-name`的操作，就会导致抛出一个未处理的异常，因而，这条消息并没有被reject，会导致事件挂掉，并且下次依然会挂掉，导致再也不能正常工作了。。。
```
info: DotNetCore.CAP.Internal.Bootstrapper[0]
fail: DotNetCore.CAP.Internal.ConsumerRegister[0]
The given key 'cap-msg-name' was not present in the dictionary.
System.Collections.Generic.KeyNotFoundException: The given key 'cap-msg-name' was not present in the dictionary.
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at DotNetCore.CAP.Messages.TransportMessage.GetName()
at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass22_0.<RegisterMessageProcessor>b__0(Object sender, TransportMessage transportMessage)
at DotNetCore.CAP.Kafka.KafkaConsumerClient.Listening(TimeSpan timeout, …
```
> fix: log name shoud put in try

- docs/content/user-guide/en/monitoring/diagnostics.md
- docs/content/user-guide/zh/monitoring/diagnostics.md
Fixed typo on page [Diagnostics => Dashboard](https://cap.dotnetcore.xyz/user-guide/en/monitoring/diagnostics/#monitor-with-dashboard).
`x.UserDashboard() ==> x.UseDashboard()`
> Fixed typo.

- samples/Sample.RabbitMQ.SqlServer/Startup.cs
- src/DotNetCore.CAP.RabbitMQ/CAP.RabbiMQOptions.cs
- src/DotNetCore.CAP.RabbitMQ/RabbitMQConsumerClient.cs
feature: add basicQos options to control the basic channel of RabbitMq and enforce qos parameters.
This feature is a much needed option and a simple one to implement for RabbitMQ control of the basicQos channel.
The reason why the need for this setup:in my opinion is a much needed option due to the fact that sometimes we need to control the flow of the messages consumed to allow for lesser memory footprint on some big queues with some big messages workload that cannot be coped with the rabbit speed of delivery to consume those messages.
I would like to know if is possible to add this change also from at least 6.2.1 as there are still some projects in the .net 6 version?
Thanks to: @rafaelpadovezi / @ricardochaves  helping sorting this out
> add basicQos options to control the basic channel of RabbitMq and enforce qos parameters

- src/DotNetCore.CAP.RabbitMQ/CAP.RabbiMQOptions.cs
- src/DotNetCore.CAP.RabbitMQ/RabbitMQConsumerClient.cs
Added an option to change the consumer queue type if required as I needed support for quorum queues.
https://www.rabbitmq.com/quorum-queues.html
> Added option to set the queue type for RabbitMQ

- CAP.sln
- samples/Sample.AzureServiceBus.InMemory/Contracts/DomainEvents/Contract.cs
- samples/Sample.AzureServiceBus.InMemory/Contracts/IntegrationEvents/Contract.cs
- samples/Sample.AzureServiceBus.InMemory/Program.cs
- samples/Sample.AzureServiceBus.InMemory/Properties/launchSettings.json
- src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerClient.cs
- src/DotNetCore.CAP.AzureServiceBus/CAP.AzureServiceBusOptions.cs
- src/DotNetCore.CAP.AzureServiceBus/DotNetCore.CAP.AzureServiceBus.csproj
- src/DotNetCore.CAP.AzureServiceBus/ITransport.AzureServiceBus.cs
- src/DotNetCore.CAP.AzureServiceBus/Producer/IServiceBusProducerDescriptor.cs
- src/DotNetCore.CAP.AzureServiceBus/Producer/IServiceBusProducerDescriptorFactory.cs
- src/DotNetCore.CAP.AzureServiceBus/Producer/ServiceBusProducerDescriptorBuilder.cs
- test/DotNetCore.CAP.AzureServiceBus.Test/DotNetCore.CAP.AzureServiceBus.Test.csproj
- test/DotNetCore.CAP.AzureServiceBus.Test/Producer/ServiceBusProducerBuilderTests.cs
- test/DotNetCore.CAP.AzureServiceBus.Test/ServiceBusTransportTests.cs
This is a continuation of the work that was started by @mviegas in #1139, rebased on top of the latest changes in the master branch. The PR adds the possibility of publishing to multiple Azure Service Bus Topics inside the same Azure Service Bus instance by specifying a custom topic by message type, providing partial support for #1074.
```csharp
capOptions.UseAzureServiceBus(asb =>
{
// other configuration
asb.ConfigureCustomProducer<EntityCreatedForIntegration>(cfg => cfg.WithTopic("entity-created"));
});
```
Message types that don't have a custom producer configuration will use the default `TopicPath`.
> Allow publishing to multiple Service Bus topics (attempt 2)

- src/DotNetCore.CAP.RabbitMQ/CAP.RabbiMQOptions.cs
1. remove redundant default value assignment for properties (54a942e4f31f1cedadf9fa7593a93884081a48cb)
2. remove unused private setters (29f9e4e65dd8931aeb841167db5292d7785e6a04)
> redundant code in BasicQos

- src/DotNetCore.CAP.RedisStreams/IConnectionPool.Default.cs
- src/DotNetCore.CAP.RedisStreams/IConnectionPool.LazyConnection.cs
order connections in the connection pool by applying order for non-lazy-created connections
- [#1324 ]
> order pool connections non-lazy created connections

- src/DotNetCore.CAP/Internal/Helper.cs
- src/DotNetCore.CAP/Internal/ISubscribeExector.Default.cs
- src/DotNetCore.CAP/Internal/ISubscribeInvoker.Default.cs
1. Modify the problem of losing stack information when an exception is thrown after implementing the ISubscribeFilter interface.
2. Modify the problem of losing stack information when an exception is thrown in the InvokeConsumerMethodAsync method.
- None
- SubscribeInvoker.InvokeAsync
- SubscribeExecutor.InvokeConsumerMethodAsync
- None
- None
- None
> Preserve stack information when an exception is thrown.

- docs/content/user-guide/en/transport/azure-service-bus.md
- src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerClient.cs
- src/DotNetCore.CAP.AzureServiceBus/CAP.AzureServiceBusOptions.cs
When creating a topic subscription an AutoDeleteOnIdle timeout can be configured. This PR exposes this option in the CAP AzureServiceBusOptions.
- https://github.com/dotnetcore/CAP/issues/1347
- Add `SubscriptionAutoDeleteOnIdle` option to the `AzureServiceBusOptions`
- Pass option in the `AzureServiceBusConsumerClient` when creating a subscription.
- DotNetCore.CAP.AzureServiceBus
_Provide a step-by-step guide on how to test your changes. Include any relevant information like environment setup, dependencies, etc._
> Azure Service Bus: subscription autodelete on idle

- src/DotNetCore.CAP/Processor/IProcessor.NeedRetry.cs
When the first retry exceeds 60 seconds, MessageNeedToRetryProcessor will be repeatedly called many times.
- https://github.com/dotnetcore/CAP/issues/1353
- When the previous retry has not completed, the lock time is extended and a waiting period of 60 seconds is required.
- MessageNeedToRetryProcessor
> Env: MongoDB+RabbitMQ
MessageNeedToRetryProcessor.cs 
```csharp
public virtual async Task ProcessAsync(ProcessingContext context)
{
if (context == null) throw new ArgumentNullException(nameof(context));
var storage = context.Provider.GetRequiredService<IDataStorage>();
_ = Task.Run(() => ProcessPublishedAsync(storage, context));
// add this line to log called times
Console.WriteLine($"Trigger Retry Processor {DateTime.Now}");
if (_options.Value.UseStorageLock && _failedRetryConsumeTask is …
```
> fix retry processor bug

- src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerClient.cs
- src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerCommitInput.cs
- src/DotNetCore.CAP.AzureServiceBus/ServiceBusProcessorFacade.cs
Having both producer and consumer using CAP on top of Azure Service Bus, both of them having sessions enabled. This causes exceptions on consumer side
```
- Exception: System.InvalidOperationException: It is not possible for an entity that requires sessions to create a non-sessionful message receiver. TrackingId:<private>, SystemTracker:<private>
For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ReceiveMessagesAsyncInternal(Int32 maxMessages, Nullable`1 maxWaitTime, TimeSpan timeout, CancellationToken cancellationToken)
at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<ReceiveMessagesAsync>b__41_0>d.MoveNext()
--- End of stack trace from previous location ---
at …
```
> Adding facade to enable session processing

- src/DotNetCore.CAP.OpenTelemetry/DiagnosticListener.cs
"Event Persistence" span doesn't get context if a parent transaction is running (for example, an http request handled by a controller).
Since .Net 7, OpenTelemetry activity source name have changed to "Microsoft.AspNetCore"
cf https://github.com/open-telemetry/opentelemetry-dotnet/blob/3c2bb7c93dd2e697636479a1882f49bb0c4a362e/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L48
To a larger extent, "Event Persistence" span should be linked to a parent activity if exisit
- DotNetCore.CAP.OpenTelemetry
> Fix parent span for "Event Persistence" activity trace

- samples/Sample.AzureServiceBus.InMemory/Program.cs
- src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerClient.cs
- src/DotNetCore.CAP.AzureServiceBus/Producer/IServiceBusProducerDescriptor.cs
- src/DotNetCore.CAP.AzureServiceBus/Producer/ServiceBusProducerDescriptorBuilder.cs
- test/DotNetCore.CAP.AzureServiceBus.Test/Producer/ServiceBusProducerBuilderTests.cs
- test/DotNetCore.CAP.AzureServiceBus.Test/ServiceBusTransportTests.cs
For azure service bus - `.ConfigureCustomProducer` does not imply it would create a new subscription, this PR is intended to introduce a `.WithSubscription` method to explicitly state that a subscription is needed while still maintaining backward compatibility.
Problem with subscription - if there are no suited consumers - CAP with throw exception, consider a scenario where a service consumes from `topic-a` and posts to `topic-b` via `ConfigureCustomProducer`. There are no expectations where service will consume events from `topic-b` so creating subscription is not needed.
-  Updated `ServiceBusProducerDescriptorBuilder.cs` by introducing `UseTopic` and `WithSubscription` methods while maintaining backward compatibility for `ConfigureCustomProducer` method
- …
> Be able to configure if to subscribe to custom producer topic

- src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerClient.cs
Removing double registration of event handler for azure service bus
- Double registration causes errors on opening connection
- Removed double registration in azure service bus consumer client
- AzureServiceBusConsumerClient.cs
> Removing double registration of event handler

- src/DotNetCore.CAP.OpenTelemetry/DiagnosticListener.cs
- src/DotNetCore.CAP/Transport/BrokerAddress.cs
Open telemetry diagnostic listener fails when Azure service bus is used without a connection string.
Azure service bus supports automatic connections when using managed identities, so you don't have to specify connection string. Diagnostic listener has this code that throws a null reference as BrokerAddress.Endpoint is null.
- https://github.com/dotnetcore/CAP/issues/1432
- BrokerAddress.Endpoint is never null, fallbacks to String.Empty
- BrokerAddress.cs
> Open telemetry subscriber thows null reference when using azure service bus without connection string

- src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs
Add memory barrier to _disposed field to make Dispose call thread safe
When doing Integration testing with WebApplicationFactory Class using xunit, tests tear down dispose twice.
One by CancelationToken, with stop method. This first call make CancelationTokenSource disposed, and every thing is fine.
After that WebApplicationFactory  is then disposed, and also call ConsumerRegister.Dispose.
Due to race condition, Pulse method is called a second time and try to dispose already disposed CancellationTokenSource.
It seems to be related to https://github.com/dotnet/aspnetcore/issues/40271
- DotNetCore.CAP.Internal.ConsumerRegister.Dispose have been made thread safe
- DotNetCore.CAP.Internal.ConsumerRegister
Add an Integration Test project with a WebApplicationFactory, run in Debug mode, …
> Update IConsumerRegister.Default.cs to make dispose thread safe

- src/DotNetCore.CAP.InMemoryStorage/IDataStorage.InMemory.cs
Outbox pattern did not work as expected when using DotNetCore.CAP.InMemoryStorage, since Origin was null causing exceptions later on.
E.g. when method GetPublishedMessagesOfNeedRetry() in class InMemoryStorage returns the base class MediumMessage the required Origin property will not be set as compared to storage providers like SQL. The IDataStorage.SqlServer GetPublishedMessagesOfNeedRetry() returns MediumMessages with the Origin property set based the a deserialized Content property value. However the serialization/deserialization part can be ignored for InMemoryStorage.cs, since it will not be written to a database, therefore the Origin property can be be set immediately when storing the message instead in StoreMessageAsync().
#1439 
- Set Origin property of Memory message in …
> Set Origin property when creating new MemoryMessage for DotNetCore.CAP.InMemoryStorage

- src/DotNetCore.CAP.NATS/NATSConsumerClient.cs
See description in related issue #1449
- Removed explicit message check with null check, since crucial error message was missed.
- DotNetCore.Cap.NATS
- Specifically consumers
See related issue
> Removed explicit message check with null check.

- src/DotNetCore.CAP/Internal/ISubscribeExector.Default.cs
If we have a message in the datastore pending retry, and we no longer have the subscriber, the message is never cleared from the data store and retried forever.
This can happen during software updates for example (Subscriber removed but pending messages are still in the data store).
Since the message was not updated in the datastore, the message would be retried forever.
Fix by calling SetFailedState which will update the msg in the datastore.
I think this handling was similar in the past and was lost in some refactoring. SetFailedState still has the handling to set retries to the max retries, so that such messages are not retried either.
- Fix infinite retry of messages after subscriber is removed.
- Subscriber / Retry handling
- publish a message that has a subscriber, fail in the …
> Fix: message retried forever SubscriberNotFound

- docs/content/user-guide/en/cap/configuration.md
- docs/content/user-guide/en/cap/messaging.md
- src/DotNetCore.CAP.InMemoryStorage/IDataStorage.InMemory.cs
- src/DotNetCore.CAP.MongoDB/IDataStorage.MongoDB.cs
- src/DotNetCore.CAP.MySql/IDataStorage.MySql.cs
- src/DotNetCore.CAP.PostgreSql/IDataStorage.PostgreSql.cs
- src/DotNetCore.CAP.SqlServer/IDataStorage.SqlServer.cs
- src/DotNetCore.CAP/CAP.Options.cs
- src/DotNetCore.CAP/Persistence/IDataStorage.cs
- src/DotNetCore.CAP/Processor/IProcessor.NeedRetry.cs
For failed messages after the first 3 retries, there was a cooldown time of **4 minutes** that could not be changed. This commit request has it as an option that you can set when configuring CAP. 
- Have not opened an issue because I solved it directly 
- Added Option RetryCoolDownSeconds 
- Added argument coolDownTime of type Timespan in GetPublishedMessagesOfNeedRetry
- Added argument coolDownTime of type Timespan in GetReceivedMessagesOfNeedRetry
- Changed IProcessor.NeedRetry to call above functions using the RetryCoolDownSeconds as argument . 
- DotNetCore.Cap
- DotNetCore.Cap.InMemoryStorage
- DotNetCore.Cap.MongoDB
- DotNetCore.Cap.MySql
- DotNetCore.Cap.PostgreSql
- DotNetCore.Cap.SqlServer
- Set RetryCoolDownSeconds option other than 240 seconds (4 minutes) when initializing cap …
> - RetryFailedMessage cooldown time is now dynamic and configurable.

- src/DotNetCore.CAP.Dashboard/RouteActionProvider.cs
/ping and /health endpoints should allow anonymous requests as they are mainly used for determining if a service contains any cap endpoints
- Fixes [1471](https://github.com/dotnetcore/CAP/issues/1471)
- Make /ping endpoint to allow anonymous requests.
- Dashboard
- Call /ping and /health endpoints without authorization metadata (cookies, auth headers, etc.) while authorization is enabled and expect the requests are succeeded.
- [x ] My changes follow the project's code style guidelines
> Make /ping and /health endpoints to allow anonymous requests

- src/DotNetCore.CAP.Dashboard/GatewayProxy/GatewayProxyAgent.cs
In the k8n discovery mode service address is split into two parts one is the HTTP address and the other one is the port. So the port is never included in the service address. `GatewayProxyAgent` assumes that if an address starts with `http` it must be a full address and ignores the port and this causes a request to a nonexistent address. This PR fixes the issue by respecting the port info that comes from the node discovery.
- Dashboard
- Use k8n node discovery in a cluster where services run on different ports than 80 and switch from dashboard.
> Respect the node port while configuring downstream request (GatewayProxyAgent)

- src/DotNetCore.CAP.Dashboard/wwwroot/dist/index.html
- src/DotNetCore.CAP.MongoDB/ICapTransaction.MongoDB.cs
Adds the ability to provide a custom IClientSessionHandle to the MongoDB data provider
None
- Adds another override to StartTransaction of MongoDB provider to allow a custom IClientSessionHandle instead of creating one on the spot.
- MongoDB Storage Provider
Provide a custom IClientSessionHandle to the StartTransaction method
> Allow custom session handle

- src/DotNetCore.CAP/Internal/ConsumerContext.cs
- src/DotNetCore.CAP/Internal/ISubscribeExector.Default.cs
- test/DotNetCore.CAP.Test/SubscribeInvokerTest.cs
- test/DotNetCore.CAP.Test/SubscribeInvokerWithCancellation.cs
By including the MediumMessage, we give consumers more options for handling in the subscribe filter, for example to implement rules based on the number of retries already done, or to set disable retrying a message under some circumstances.
- https://github.com/dotnetcore/CAP/issues/1377
- adding MediumMessage to ConsumerContext
- ConsumerContext
- SubscribeFilter
Use MediumMessage in a SubscribeFilter
=> Personally I want this to be able to set the Retries to the max so a message is not retried. It's a bit of a hack and I don't know if this should be made an officially sanctioned functionality by adding it to the documentation. 
> Include MediumMessage in ConsumerContext

- docs/content/user-guide/en/storage/postgresql.md
- src/DotNetCore.CAP.PostgreSql/CAP.PostgreSqlOptions.cs
- src/DotNetCore.CAP.PostgreSql/IDataStorage.PostgreSql.cs
- src/DotNetCore.CAP.PostgreSql/IMonitoringApi.PostgreSql.cs
- src/DotNetCore.CAP.PostgreSql/IStorageInitializer.PostgreSql.cs
Add an optional DataSource property in the PostgreSqlOptions. Using a data source will allow users of CAP to configure the full range of Npgsql options without having to expose each one in the CAP API. In particular, this allows to configure [dynamic password rotation](https://www.npgsql.org/doc/security.html#auth-token-rotation-and-dynamic-password) needed when authenticating against certain databases hosted in the cloud.
- #1310
- Allow configuration of `NpgsqlDataSource` through a new `DataSource` property in `PostgreSqlOptions`.
- Create `NpgsqlConnection` from data source if there is one, otherwise fall back to using the connection string
- PostgresSQL
The new data source configuration can be tested like this:
```csharp
var dataSource = new …
```
> Allow configuring PostgreSQL using an Npgsql data source

- src/DotNetCore.CAP/Internal/ICapPublisher.Default.cs
Fixed bug that causes CapPublisher to hold finished transactions resulting in incorrect publishing behavior
[Related issue](https://github.com/dotnetcore/CAP/issues/1521)
Changes:
Changed Transaction null check in CapPublisher
It can be tested via Sample.Kafka.PostgreSql. After Moving event publishing outside of transaction scope, event will be sent immediately or with a correct delay (if given).
> Fix: Transaction is nullified after finishing the scope

- src/DotNetCore.CAP.NATS/CAP.NATSOptions.cs
- src/DotNetCore.CAP.NATS/NATSConsumerClient.cs
With these changes a consumer of the DotNetCore.CAP.NATS nuget package can opt out from allowing a NATS Consumer client to create topics and streams dynamically which enforces each client to be granted "admin" like permissions. To avoid assigning these permissions to each client, a consumer of the nuget package can now opt out from this by specifying NATSOptions property `EnableSubscriberClientStreamAndSubjectCreation` to `false` (defaults to true).
- #1545 
- Added new `NATSOptions` property `EnableSubscriberClientStreamAndSubjectCreation` and usage of it in `NatsConsumerClient.FetchTopics` method.
- Added call to `OnLogCallback` with `MqLogType.ConnectError` in order to mark the `ConsumerRegister` as "unhealthy" to allow "subscribe retries" calls to the `NatsConsumerClinet.Subscribe` …
> Nats improvement 1545

- src/DotNetCore.CAP/Processor/IDispatcher.Default.cs
fix retry event execute more than FailedRetryCount
- #1559 
- only `message.Retries=0` can use channel to parallel execute 
- All
- [ x ] I have tested my changes locally
- [ x ] My changes follow the project's code style guidelines
- _Mention any reviewers you would like to review your PR. This can be helpful if you know someone who is familiar with the part of the codebase you're working on._
> fix: retry received event just execute directly

- src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerClient.cs
- src/DotNetCore.CAP.AzureServiceBus/Helpers/ServiceBusHelpers.cs
- src/DotNetCore.CAP.AzureServiceBus/ITransport.AzureServiceBus.cs
- test/DotNetCore.CAP.AzureServiceBus.Test/Helpers/ServiceBusHelperTests.cs
- test/DotNetCore.CAP.AzureServiceBus.Test/ServiceBusTransportTests.cs
This PR fixes an issue identified in #1571 where the BrokerAddress property had a wrong value when authenticating with TokenCredential instead of ConnectionString.
No specific issue was opened.
- Added:
- `ServiceBusHelpers` class with helper methods and test class `ServiceBusHelpersTests`.
- Tests to verify BrokerAddress property in `ServiceBusTransportTests` class.
- Changed:
- BrokerAddress property getter in classes `AzureServiceBusConsumerClient` and `ITransport.AzureServiceBus`.
- Azure Service Bus transport.
- N/A.
@yang-xiaodong
> fix: BrokerAddress property in AzureServiceBus transport

- src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerClient.cs
- src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerCommitInput.cs
When using Azure Service Bus, messages are marked as completed even if the system fails to persist the received message to the database.
- [Azure Service Bus Messages Marked as Completed Even When Persistence Fails](https://github.com/dotnetcore/CAP/issues/1583)
- Call AbandonMessageAsync on Azure Service Bus message when persistence fails to avoid message loss.
- DotNetCore.CAP.AzureServiceBus
> fix(#1583): Call AbandonMessageAsync on Azure Service Bus message when persistence fails to avoid message loss

- docs/content/user-guide/en/transport/rabbitmq.md
- docs/content/user-guide/zh/transport/rabbitmq.md
- src/DotNetCore.CAP.RabbitMQ/CAP.RabbiMQOptions.cs
- src/DotNetCore.CAP.RabbitMQ/RabbitMQConsumerClient.cs
I have a use case where transient services that are non competing consumers (consumer group GUID) have to use the queue system to get some push events from other services. These queues are created but never deleted when the service stops to come back in a later time. When the service gets back up it creates a new GUID consumer group, so a new queue. For the moment I am manually deleting these using the RabbitMQ management API so each service when starts, checks for queues with 0 consumers. 
My actual solution is hacky and doesn't work every time. 
_With my ugly hacky implementation there is a problem because sometimes when 2 services start up at the same time, each create its queue but the consumers threads haven't connected yet so the queue gets deleted by the other service. This could …
> added control for queue options in RabbitMQ transport

- docs/content/user-guide/en/monitoring/kubernetes.md
- docs/content/user-guide/zh/monitoring/kubernetes.md
- src/DotNetCore.CAP.Dashboard.K8s/K8sDiscoveryOptions.cs
- src/DotNetCore.CAP.Dashboard.K8s/K8sNodeDiscoveryProvider.cs
The K8s discovery was working ok but not great for a real life scenario use case. There were the following problems: 
- The security was not great because if you gave someone (a dev) access to use the dashboard, he could switch to any service inside any namespace in the k8s cluster. 
- There were many services listed in the nodes section and most of those don't even have a CAP so they just bloat the list and give an Error if switched to. 
- The listed services always did use the first found port defined in the k8s-service. This needed to change because sometimes when using tools to create your deployments and k8s-services you cannot control the order of the ports of the service. 
Changes in this PR address the above issues by doing the following measures: 
- Allowing to list nodes without …
> K8S node discovery with filtering options

- src/DotNetCore.CAP/ICapTransaction.Base.cs
- src/DotNetCore.CAP/Internal/ICapPublisher.Default.cs
Changed DateTime.ToString() calls to DateTime.ToString(CultureInfo.InvariantCulture).
This will fix issue about producing and consuming with different cultures.
#1588 
cap-sent-time is now converted with invariant culture
PublishInternalAsync and Transaction.Flush()
When changing culture of your application cap-sent-time should not change format.
- [✓] I have tested my changes locally
- [✓ ] I have added necessary documentation (if applicable)
- [ ✓] I have updated the relevant tests (if applicable)
- [ ✓] My changes follow the project's code style guidelines
> Fix: DateTime parsing with InvariantCulture

- src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerClient.cs
SemaphoreSlim not released after message commit or reject when GroupConcurrent is enabled.
- #1596
> Fix a bug that when set GroupConcurrent does not work in Azure Service Bus

- src/DotNetCore.CAP.MySql/IDataStorage.MySql.cs
- src/DotNetCore.CAP.MySql/IMonitoringApi.MySql.cs
- src/DotNetCore.CAP.MySql/IStorageInitializer.MySql.cs
- src/DotNetCore.CAP.PostgreSql/IDataStorage.PostgreSql.cs
- src/DotNetCore.CAP.PostgreSql/IMonitoringApi.PostgreSql.cs
- src/DotNetCore.CAP.PostgreSql/IStorageInitializer.PostgreSql.cs
- src/DotNetCore.CAP.SqlServer/IDataStorage.SqlServer.cs
- src/DotNetCore.CAP.SqlServer/IMonitoringApi.SqlServer.cs
- src/DotNetCore.CAP.SqlServer/IStorageInitializer.SqlServer.cs
Add table-building default indexes to database storage and adjust query SQL to use optimized indexes.
- #1599
-  Table Creation and Queries for SQL Server, MySQL, PostgreSQL
- Storage Component
> Add default indexes to the database tables during creation

- src/DotNetCore.CAP.MongoDB/IStorageInitializer.MongoDB.cs
Updated mongo initializer to change the way how indexes are created. Included missing index based on mongo Altas recommendations.
* Indexes are now created using explicit generic
* Removed index existence check, MongoDB does it automatically (https://www.mongodb.com/docs/manual/reference/method/db.collection.createIndexes/#recreating-an-existing-index)
* Removed Background index option, as it was deprecated and is no longer used by MongoDB (https://www.mongodb.com/docs/manual/core/index-creation/#comparison-to-foreground-and-background-builds)
* Added StatusName_1_ExpiresAt_1 index as per MongoDB Atlas performance advisor
* Using default mongodb naming for indexes
* MongoDBStorageInitializer
Run CAP that is using mongodb locally and wait for initializer to kick in
Old indexes are gonna be …
> refactored mongo initializer

- src/DotNetCore.CAP.AmazonSQS/AmazonSQSConsumerClient.cs
- src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerClient.cs
- src/DotNetCore.CAP.Kafka/KafkaConsumerClient.cs
- src/DotNetCore.CAP.NATS/NATSConsumerClient.cs
- src/DotNetCore.CAP.Pulsar/PulsarConsumerClient.cs
- src/DotNetCore.CAP.RabbitMQ/RabbitMQBasicConsumer.cs
Handle existing cap-msg-group header (by overwriting it) and tolerate duplicate headers for Kafka consumer (since testers tend to do stuff manually sometimes and mess up with message headers as well)
- https://github.com/dotnetcore/CAP/issues/1620
Produce a message to Kafka or any other supported system with cap-msg-group header
- [ ✓] I have tested my changes locally
- [ ✓] My changes follow the project's code style guidelines
> Handle existing cap-msg-group header and tolerate duplicate headers for Kafka consumer

- src/DotNetCore.CAP/Internal/ScheduledMediumMessageQueue.cs
- src/DotNetCore.CAP/Processor/IDispatcher.Default.cs
- src/DotNetCore.CAP/Transport/IDispatcher.cs
- test/DotNetCore.CAP.Test/DispatcherTests.cs
- test/DotNetCore.CAP.Test/DotNetCore.CAP.Test.csproj
- test/DotNetCore.CAP.Test/Helpers/TestThreadSafeMessageSender.cs
Introduce `ScheduledMediumMessageQueue` for thread-safe scheduling of messages. Updated `Dispatcher` to use the new queue and modified the scheduling logic for improved reliability. Added unit tests.
Fixes #1637
> Add thread-safe message scheduling and related tests

- src/DotNetCore.CAP.MongoDB/DotNetCore.CAP.MongoDB.csproj
Upgrade dependent mongodb driver to v3.0
- upgrade dependent mongodb driver to v3.0
- DotNetCore.CAP.MongoDB
**mongo driver v3 has some changes that are not backwards compatible.**
> Upgrade dependent mongodb driver to v3.0

- src/DotNetCore.CAP.Kafka/IConnectionPool.Default.cs
修复为kafka自定义参数时，某些参数无法被正确设置
无法设置的options: queue.buffering.max.messages, message.timeout.ms, request.timeout.ms
> 修复为kafka自定义参数时，某些参数无法被正确设置
