dotnetcore/CAP

README.md

Add English version Readme.md

---

README.md

Update README.md in develop

---

README.md
README.zh-cn.md

Fix Service Method attribute and nuget package command in readme

Fix Service Method attribute and nuget package command in readme

---

build/version.props
src/DotNetCore.CAP.Kafka/KafkaConsumerClient.cs
src/DotNetCore.CAP.MySql/CAP.EFOptions.cs
src/DotNetCore.CAP.MySql/CAP.MySqlCapOptionsExtension.cs
src/DotNetCore.CAP.MySql/CAP.MySqlOptions.cs
src/DotNetCore.CAP.MySql/CAP.Options.Extensions.cs
src/DotNetCore.CAP.MySql/DotNetCore.CAP.MySql.csproj
src/DotNetCore.CAP.MySql/MySqlStorageConnection.cs
src/DotNetCore.CAP.PostgreSql/CAP.Options.Extensions.cs
src/DotNetCore.CAP.PostgreSql/CAP.PostgreSqlCapOptionsExtension.cs
src/DotNetCore.CAP.PostgreSql/DotNetCore.CAP.PostgreSql.csproj
src/DotNetCore.CAP.SqlServer/CAP.Options.Extensions.cs
src/DotNetCore.CAP.SqlServer/CAP.SqlServerCapOptionsExtension.cs
src/DotNetCore.CAP.SqlServer/SqlServerStorage.cs
src/DotNetCore.CAP/DotNetCore.CAP.csproj
src/DotNetCore.CAP/IQueueExecutor.Subscribe.cs
test/DotNetCore.CAP.MySql.Test/DotNetCore.CAP.MySql.Test.csproj
test/DotNetCore.CAP.PostgreSql.Test/DotNetCore.CAP.PostgreSql.Test.csproj
test/DotNetCore.CAP.SqlServer.Test/DotNetCore.CAP.SqlServer.Test.csproj
test/DotNetCore.CAP.Test/DotNetCore.CAP.Test.csproj

* Remove `TableNamePrefix` option from `MySqlOptions` to `EFOptions`.
* Upgrade nuget package
* Fixed the connection bug of getting message from table. (#83)
* Fixed entityframework rename table name prefix bug. (#84)
* Fixed sql server scripts bug of create table scheme. (#85)
* Fixed thread safety issue about KafkaOptions.(#89)

Release version 2.1.4

---

build/version.props
src/DotNetCore.CAP/Diagnostics/DiagnosticListenerExtensions.cs
src/DotNetCore.CAP/Diagnostics/EventData.Broker.cs
src/DotNetCore.CAP/IPublishMessageSender.Base.cs

fixed message enqueue exception in v2.2

Release 2.2.1

---

src/DotNetCore.CAP/Internal/IConsumerServiceSelector.Default.cs

solve the problem of issue#181

---

src/DotNetCore.CAP.MongoDB/IStorage.MongoDB.cs

Adding indexes to collections.

DotNetCore.CAP.MongoDB: added index.

---

src/DotNetCore.CAP/Diagnostics/DiagnosticListenerExtensions.cs
src/DotNetCore.CAP/Diagnostics/EventData.Broker.PublishError.cs
src/DotNetCore.CAP/Diagnostics/EventData.SubscriberInvokeError.cs
src/DotNetCore.CAP/IPublishMessageSender.Base.cs
src/DotNetCore.CAP/ISubscribeExecutor.Default.cs
test/DotNetCore.CAP.Test/DiagnosticsTest.cs

Passing retries count into CapErrorSubscriberInvoke and CapErrorPublish events

Diagnostic retries

---

src/DotNetCore.CAP/Dashboard/CombinedResourceDispatcher.cs
src/DotNetCore.CAP/Dashboard/EmbeddedResourceDispatcher.cs

Fixed Net Core 3.0，Dashboard Can't Load Js And Css.(#404)

Fixed Net Core 3.0，Dashboard Can't Load Js And Css.

---

src/DotNetCore.CAP.MySql/IStorage.MySql.cs

add index to ExpiresAt

---

docs/content/user-guide/en/cap/configuration.md
docs/content/user-guide/zh/cap/configuration.md

fixed docs typo

---

samples/Sample.Kafka.PostgreSql/Sample.Kafka.PostgreSql.csproj
samples/Sample.RabbitMQ.MySql/Sample.RabbitMQ.MySql.csproj
samples/Sample.RabbitMQ.SqlServer/Sample.RabbitMQ.SqlServer.csproj
src/DotNetCore.CAP.MySql/DotNetCore.CAP.MySql.csproj
src/DotNetCore.CAP.MySql/IDataStorage.MySql.cs
src/DotNetCore.CAP.MySql/IDbConnectionExtensions.cs
src/DotNetCore.CAP.MySql/IMonitoringApi.MySql.cs
src/DotNetCore.CAP.MySql/IStorageInitializer.MySql.cs
src/DotNetCore.CAP.PostgreSql/DotNetCore.CAP.PostgreSql.csproj
src/DotNetCore.CAP.PostgreSql/IDataStorage.PostgreSql.cs
src/DotNetCore.CAP.PostgreSql/IDbConnectionExtensions.cs
src/DotNetCore.CAP.PostgreSql/IMonitoringApi.PostgreSql.cs
src/DotNetCore.CAP.PostgreSql/IStorageInitializer.PostgreSql.cs
src/DotNetCore.CAP.SqlServer/DotNetCore.CAP.SqlServer.csproj
src/DotNetCore.CAP.SqlServer/IDataStorage.SqlServer.cs
src/DotNetCore.CAP.SqlServer/IDbConnectionExtensions.cs
src/DotNetCore.CAP.SqlServer/IMonitoringApi.SqlServer.cs
src/DotNetCore.CAP.SqlServer/IStorageInitializer.SqlServer.cs
src/DotNetCore.CAP/Persistence/IDbConnectionExtensions.cs
test/DotNetCore.CAP.MySql.Test/DotNetCore.CAP.MySql.Test.csproj

replace dapper with ado.net

---

src/DotNetCore.CAP.PostgreSql/IDbContextTransaction.CAP.cs

fix DotNetCore.CAP.PostgreSql.CapEFDbTransaction  RollbackAsync Method.

---

src/DotNetCore.CAP/Internal/ConsumerExecutorDescriptor.cs
src/DotNetCore.CAP/Internal/IConsumerServiceSelector.Default.cs

Added comparer to remove duplicate ConsumerExecutors.

---

src/DotNetCore.CAP.Dashboard/CAP.DashboardOptionsExtensions.cs
src/DotNetCore.CAP.Dashboard/DashboardRoutes.cs
src/DotNetCore.CAP.InMemoryStorage/IDataStorage.InMemory.cs
src/DotNetCore.CAP.MongoDB/IDataStorage.MongoDB.cs
src/DotNetCore.CAP.MySql/IDataStorage.MySql.cs
src/DotNetCore.CAP.PostgreSql/IDataStorage.PostgreSql.cs
src/DotNetCore.CAP.SqlServer/IDataStorage.SqlServer.cs
src/DotNetCore.CAP/DotNetCore.CAP.csproj
src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs
src/DotNetCore.CAP/Internal/ISubscribeInvoker.Default.cs
src/DotNetCore.CAP/Messages/Message.cs
src/DotNetCore.CAP/Serialization/ISerializer.JsonUtf8.cs
src/DotNetCore.CAP/Serialization/ISerializer.cs
test/DotNetCore.CAP.MySql.Test/MySqlStorageConnectionTest.cs
test/DotNetCore.CAP.MySql.Test/TestHost.cs
test/DotNetCore.CAP.Test/MessageTest.cs
test/DotNetCore.CAP.Test/SubscribeInvokerTest.cs

This should solve issue #641 
It has been thoroughly tested using a MongoDB as datastore. Added some additional Tests to the Test project but didn't test it with al the other different datastores.

Solve the issue of being restricted to using Newtonsoft

---

src/DotNetCore.CAP/Internal/ISubscribeInvoker.Default.cs

Solve the issue of being duplicated executors from different assemblies

---

src/DotNetCore.CAP.AzureServiceBus/ITransport.AzureServiceBus.cs
src/DotNetCore.CAP/Messages/TransportMessage.cs

Fix for: https://github.com/dotnetcore/CAP/issues/668

Set correlation Id for azure service bus message

---

src/DotNetCore.CAP/Internal/ISubscribeInvoker.Default.cs

fixes issue [#695](https://github.com/dotnetcore/CAP/issues/695)

Executor key not unique

---

src/DotNetCore.CAP/Internal/ISubscribeInvoker.Default.cs

Executor key change lead to possible null reference exception

---

src/DotNetCore.CAP.PostgreSql/IDataStorage.PostgreSql.cs

- fix postgresql delete expires sql incorrect SQL statement

fix postgresql delete expires data logic error

---

docs/content/user-guide/en/storage/sqlserver.md

Changed the misprint of Postgre to SqlServer

Update sqlserver.md misprint

---

src/DotNetCore.CAP.AmazonSQS/AmazonSQSConsumerClient.cs
src/DotNetCore.CAP.Dashboard/DotNetCore.CAP.Dashboard.csproj
src/DotNetCore.CAP.Dashboard/JsonDispatcher.cs
src/DotNetCore.CAP.Dashboard/JsonStats.cs
src/DotNetCore.CAP.Dashboard/Pages/HomePage.cshtml
src/DotNetCore.CAP.Dashboard/Pages/HomePage.generated.cs
src/DotNetCore.CAP/DotNetCore.CAP.csproj
src/DotNetCore.CAP/Serialization/ISerializer.JsonUtf8.cs

Replace Newtonsoft.Json to System.Text.Json

---

src/DotNetCore.CAP.RabbitMQ/ITransport.RabbitMQ.cs

Enabling Publisher Confirms on RabbitMQ

---

src/DotNetCore.CAP/Internal/IConsumerServiceSelector.Default.cs

Support query subscription from DI implementation factory

---

src/DotNetCore.CAP.AmazonSQS/ITransport.AmazonSQS.cs

This PR contains the fixes for two issues we faced:
- If we have more than 100 topics, then AWS SDK returns a token to get the next 100 rows. This was missing.
- The first issue wasn't easy to recognize as a message is being marked as succeeded but the message actually wasn't sent in case if the topic is missing.

Fixes for SNS transport implementation

---

docs/content/user-guide/en/getting-started/quick-start.md
docs/content/user-guide/zh/getting-started/quick-start.md

Change from `FromService` to `FromServices`.
Ref:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.fromservicesattribute

Fix attribute in Quick Start

---

src/DotNetCore.CAP.Kafka/IProcessingServer.AutoCreateTopic.cs

Please see my issue https://github.com/dotnetcore/CAP/issues/809

Add KafkaOptions.MainConfig to AutoCreateTopic

---

src/DotNetCore.CAP.Dashboard/JsonSerializeOptions.cs
src/DotNetCore.CAP.Dashboard/JsonStats.cs
src/DotNetCore.CAP.Dashboard/Pages/HomePage.cshtml

This PR is to fix dashboard page not update problem，It looks like due to change the JsonSerializer, cause  js exception

Fix Dashboard metric not update #811

---

docs/content/user-guide/en/monitoring/dashboard.md
docs/content/user-guide/zh/monitoring/dashboard.md

Update Dashboard documentation to match change made to
`IDashboardAuthorizationFilter` in https://github.com/dotnetcore/CAP/pull/390.

Update Dashboard documentation

---

samples/Sample.Dashboard.Blazor/Pages/_Host.cshtml
samples/Sample.Dashboard.Blazor/Startup.cs
src/DotNetCore.CAP.UI/DotNetCore.CAP.UI.csproj
src/DotNetCore.CAP.UI/Shared/MainLayout.razor

Dashboard blazor

---

src/DotNetCore.CAP.SqlServer/IDbContextTransaction.CAP.cs

Resolves #867. Enables access to the underlying transaction when using Entity Framework.

Implement IInfrastructure` on CapEFDbTransaction

---

samples/Sample.RabbitMQ.SqlServer/Startup.cs
src/DotNetCore.CAP/CAP.Options.cs
src/DotNetCore.CAP/Serialization/ISerializer.JsonUtf8.cs
test/DotNetCore.CAP.Test/MessageTest.cs

Added option to configure JSON serialization settings

---

src/DotNetCore.CAP/Internal/Filter/SubscribeFilter.cs

An abstract base class implementation will be useful for ISubscribeFilter like as ISaveChangesInterceptor and SaveChangesInterceptor in entity framework core.

Abstract base class for ISubscribeFilter

---

src/DotNetCore.CAP.RabbitMQ/RabbitMQConsumerClient.cs
src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs
src/DotNetCore.CAP/Processor/IDispatcher.Default.cs

Improve flow control for message of in memory

---

src/DotNetCore.CAP.Dashboard/UiMiddleware.cs
src/DotNetCore.CAP/Internal/SnowflakeId.cs

Cache UiMiddleware's url check regex;

Check _snowflakeId instance before locking;

---

src/DotNetCore.CAP.RedisStreams/IRedisStream.Manager.Default.cs
src/DotNetCore.CAP.RedisStreams/IRedisStream.Manager.Extensions.cs

Use KeyExistsAsync for exists check

Use KeyExistsAsync for exists check

---

src/DotNetCore.CAP.Kafka/CAP.KafkaOptions.cs
src/DotNetCore.CAP.Kafka/KafkaConsumerClient.cs
src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs
src/DotNetCore.CAP/Transport/MqLogType.cs

Fixes kafka consume excepiton for GroupLoadInProress errcode

---

samples/Sample.RabbitMQ.SqlServer/Controllers/ValuesController.cs

fixed #1122

---

src/DotNetCore.CAP.InMemoryStorage/IDataStorage.InMemory.cs
src/DotNetCore.CAP.MongoDB/IDataStorage.MongoDB.cs
src/DotNetCore.CAP.MySql/IDataStorage.MySql.cs
src/DotNetCore.CAP.PostgreSql/IDataStorage.PostgreSql.cs
src/DotNetCore.CAP.SqlServer/IDataStorage.SqlServer.cs
src/DotNetCore.CAP/CAP.Options.cs
src/DotNetCore.CAP/Internal/IMessageSender.Default.cs
src/DotNetCore.CAP/Internal/ISubscribeDispatcher.Default.cs

Add ability to configure failed messages expiration term

---

CAP.sln
samples/Samples.Redis.SqlServer/Dockerfile
samples/Samples.Redis.SqlServer/Samples.Redis.SqlServer.csproj
src/DotNetCore.CAP.RedisStreams/IConsumerClient.Redis.cs
src/DotNetCore.CAP.RedisStreams/IRedis.Events.cs
src/DotNetCore.CAP.RedisStreams/IRedisStream.Manager.Default.cs
src/DotNetCore.CAP.RedisStreams/IRedisStream.Manager.Extensions.cs
src/DotNetCore.CAP.RedisStreams/ITransport.Redis.cs
src/DotNetCore.CAP.RedisStreams/RedisErrorExtensions.cs

Change reading/creating streams and consumer groups to handle non idempotent operations

---

README.md

Add async subscription to readme

---

samples/Sample.RabbitMQ.SqlServer/AppDbContext.cs
samples/Sample.RabbitMQ.SqlServer/Startup.cs
src/DotNetCore.CAP.RabbitMQ/IConnectionChannelPool.Default.cs

support connect to RabbitMQ cluster without using default port

---

docs/content/user-guide/en/transport/general.md
docs/content/user-guide/zh/transport/general.md

Add the connection guide of the extended warehouse

update general.md for add MQTT extensions support

---

src/DotNetCore.CAP.PostgreSql/IDataStorage.PostgreSql.cs
src/DotNetCore.CAP.PostgreSql/IMonitoringApi.PostgreSql.cs
src/DotNetCore.CAP.SqlServer/IDataStorage.SqlServer.cs
src/DotNetCore.CAP.SqlServer/IMonitoringApi.SqlServer.cs

Fix MSSQL\PGSQL missing Origin

---

src/DotNetCore.CAP.InMemoryStorage/IDataStorage.InMemory.cs
src/DotNetCore.CAP.InMemoryStorage/IStorageInitializer.InMemory.cs
src/DotNetCore.CAP.MongoDB/CAP.MongoDBOptions.cs
src/DotNetCore.CAP.MongoDB/IDataStorage.MongoDB.cs
src/DotNetCore.CAP.MongoDB/IStorageInitializer.MongoDB.cs
src/DotNetCore.CAP.MongoDB/StorageMessage.cs
src/DotNetCore.CAP.MySql/IDataStorage.MySql.cs
src/DotNetCore.CAP.MySql/IStorageInitializer.MySql.cs
src/DotNetCore.CAP.PostgreSql/IDataStorage.PostgreSql.cs
src/DotNetCore.CAP.PostgreSql/IStorageInitializer.PostgreSql.cs
src/DotNetCore.CAP.SqlServer/IDataStorage.SqlServer.cs
src/DotNetCore.CAP.SqlServer/IStorageInitializer.SqlServer.cs
src/DotNetCore.CAP/CAP.Options.cs
src/DotNetCore.CAP/Persistence/IDataStorage.cs
src/DotNetCore.CAP/Persistence/IStorageInitializer.cs
src/DotNetCore.CAP/Processor/IProcessor.NeedRetry.cs

to solve this problem ： [https://github.com/dotnetcore/CAP/issues/1271](https://github.com/dotnetcore/CAP/issues/1271)
I have seen the solution in this pr：[https://github.com/dotnetcore/CAP/pull/671](https://github.com/dotnetcore/CAP/pull/671)，It needs to use the third-party component consul 
my solution only use the existing storage module in CAP , and it is simpler
test cases for related functions have been supplemented
@yang-xiaodong  Hi~ do you think this solution is feasible?

Support leader election for need retry

---

src/DotNetCore.CAP.MongoDB/IStorageInitializer.MongoDB.cs
src/DotNetCore.CAP.MySql/IStorageInitializer.MySql.cs
src/DotNetCore.CAP.PostgreSql/IStorageInitializer.PostgreSql.cs
src/DotNetCore.CAP.SqlServer/IStorageInitializer.SqlServer.cs
src/DotNetCore.CAP/Processor/IProcessor.NeedRetry.cs

solve a potentially problematic scenario in this issue: https://github.com/dotnetcore/CAP/issues/1273

fix: append version option to lock key

---

src/DotNetCore.CAP.PostgreSql/IDataStorage.PostgreSql.cs

Remove excess symbols

---

src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs

submit pr again for removing uncessary merge commit
https://github.com/dotnetcore/CAP/pull/1319
- https://github.com/dotnetcore/CAP/issues/1318

Fixes BasicQosOptions not working for RabbitMQ transport

---

src/DotNetCore.CAP.RedisStreams/CapOptions.Redis.cs

Fixes redis endpoint is null in opentelemetry

---

src/DotNetCore.CAP.OpenTelemetry/DiagnosticListener.cs

When using the _contexts dictionary to convey the context, the [IsRemote ](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activitycontext.isremote?view=net-8.0#system-diagnostics-activitycontext-isremote) flag is automatically considered false, which is why [dynatrace ](https://www.dynatrace.com/) using opentelemetry cannot bind the events correctly.
According to Microsoft documentation, the [IsRemote](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activitycontext.isremote?view=net-8.0#system-diagnostics-activitycontext-isremote) property indicates that the activity context was propagated from a remote parent.
As the message is sent to RabbitMQ by a background service, we need to create this link through propagation.
- …

fix: OpenTelemetry Dynatrace - IsRemote flag

---

samples/Sample.RabbitMQ.SqlServer/Controllers/ValuesController.cs
src/DotNetCore.CAP.SqlServer/Diagnostics/DiagnosticObserver.cs

Fixes publish delay mesage not working in transaction for sql server

---

src/DotNetCore.CAP.MongoDB/ICapTransaction.MongoDB.cs
src/DotNetCore.CAP.MySql/ICapTransaction.MySql.cs
src/DotNetCore.CAP.OpenTelemetry/DiagnosticListener.cs
src/DotNetCore.CAP.PostgreSql/ICapTransaction.PostgreSql.cs
src/DotNetCore.CAP.SqlServer/ICapTransaction.SqlServer.cs
src/DotNetCore.CAP/ICapPublisher.cs
src/DotNetCore.CAP/ICapTransaction.Base.cs
src/DotNetCore.CAP/Internal/ICapPublisher.Default.cs
test/DotNetCore.CAP.Test/CAP.BuilderTest.cs

Fixes AsyncLocal issue to support  start async transaction. 
- #1376 
- #1317 
- #1266 
- The Transaction field in the ICapPublisher interface has been changed from `Asynclocal<ICapTransaction>` to `ICapTransaction` to support start asynchronous transactions.
-  DotNetCore.CAP
_Provide a step-by-step guide on how to test your changes. Include any relevant information like environment setup, dependencies, etc._

Fixes AsyncLocal issue to support  start async transaction. 

---

docs/content/user-guide/en/monitoring/opentelemetry.md
src/DotNetCore.CAP.OpenTelemetry/DiagnosticListener.cs

Fixes an issue that caused context propagation to fail on message retry (#1452)
Before, BeforeSubscribeInvoke removed the context so it was no longer available on retry.
It also removes the _contexts dictionary, as during Subscribe this handling didn't work during retry and during Publish, the dictionary value was no longer used.
I have tested this with both aspnetcore services and console subscriber that publishes during the subscribe and context propagation was working fine. Thus #1100 is also closed, probably already in #1407.
- #1452 
- #1100
1. Fixes an issue that caused context propagation to fail on message retry (#1452)
Before, BeforeSubscribeInvoke removed the context so it was no longer available on retry.
2. Enable Baggage propagation
2. removes _context dictionary
- …

Fixes for OpenTelemetry Context Propagation

---

docs/content/user-guide/en/getting-started/introduction.md
docs/content/user-guide/zh/getting-started/introduction.md

As of November 2023, the eShop sample application has been updated and moved. 
- Update hyperlink inside docs getting started.

Update eShopOnContainer link inside docs

---

docs/content/user-guide/en/samples/github.md
docs/content/user-guide/zh/samples/github.md

Add CAP + Aspire example reference
_

Add cap-aspire documentation reference

---

src/DotNetCore.CAP.NATS/CAP.NATSCapOptionsExtension.cs
src/DotNetCore.CAP.NATS/CAP.NATSOptions.cs
src/DotNetCore.CAP.NATS/CAP.Options.Extensions.cs
src/DotNetCore.CAP.NATS/IConnectionPool.Default.cs
src/DotNetCore.CAP.NATS/IConnectionPool.cs
src/DotNetCore.CAP.NATS/ITransport.NATS.cs
src/DotNetCore.CAP.NATS/NATSConsumerClient.cs
src/DotNetCore.CAP.NATS/NATSConsumerClientFactory.cs
src/DotNetCore.CAP.RabbitMQ/RabbitMQBasicConsumer.cs
src/DotNetCore.CAP/Diagnostics/EventCounterSource.Cap.cs
src/DotNetCore.CAP/Internal/ISnowflakeId.cs

This pull request refactors the project to adopt file-scoped namespaces, enhancing code consistency and aligning with modern C# practices. The refactoring was performed using a custom Visual Studio extension that I developed and optimized specifically for this task. You can check out the extension here: [FileScopedNamespace Extension](https://marketplace.visualstudio.com/items?itemName=SamanAzadi1996.FileScopedNamespace).
I believe this change will improve the codebase's readability and maintainability. Please review and let me know if any adjustments are needed.

Refactor to file-scoped namespaces

---

src/DotNetCore.CAP.Dashboard/wwwroot/src/pages/Received.vue

refresh data after re-executed items

---

docs/content/user-guide/zh/storage/general.md

Add the implementation project address for the Dameng database in the document to save more time for projects that require Dameng database support.
-  docs/content/user-guide/zh/storage/general.md

Modify document general. md

---

docs/content/user-guide/en/cap/configuration.md

I fixed the case because it was wrong and caused an error when copying the code.
Fixed case in configuration.md
- _List the components of the project that are affected by this PR._

Fixed case in configuration.md

---

src/DotNetCore.CAP.MySql/IDataStorage.MySql.cs

fix mysql8 lock waits #1673

---

src/DotNetCore.CAP.RabbitMQ/RabbitMQBasicConsumer.cs

In case of high concurrency, the consumer now uses `ArrayPool<byte>.Shared` to copy the delivery body into a safe buffer before dispatching work to background tasks. It is required according to RabbitMQ documentation.
This avoids accessing memory that may be released by RabbitMQ after `HandleBasicDeliverAsync` returns and reduces allocations under heavy load.  
- https://github.com/dotnetcore/CAP/issues/1728 
- Copying message body immediately at the beginning of `HandleBasicDeliverAsync`.  
- Using `ArrayPool<byte>.Shared` instead of allocating a new array with `ToArray()`.  
- Ensuring buffer is safely returned to the pool in a `finally` block.  
- Updated `Consume` to work with `ReadOnlyMemory<byte>` built from the rented buffer.  
- Message consumer implementation …

Fix RabbitMQ consuming body reusing
